-- Admin bootstrap is handled at runtime by entrypoint.sh.
-- If no ADM user exists, entrypoint.sh generates a random password,
-- hashes it with bcrypt, inserts the user, and prints the credentials once to stdout.
-- Do NOT add hardcoded credentials here.
